version: "3"

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1s
      retries: 5
  websocket-server:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: "-redis redis://redis:6379"
