version: "3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
  redis-pubsub-websocket:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    command: "-redis redis://redis:6379"
